
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55000/postgres
    hikari:
      username: postgres
      password: postgrespw
  jpa:
    show-sql: true
server:
  port: 6364